import Link from "next/link";
import type { Booking, Enquiry } from "@/lib/server/db";
import { mockEquipment } from "@/data/fixtures/equipment";
import { Badge } from "@/components/ui/badge";
import { RecordActions } from "@/components/forms/RecordActions";
export function Records({bookings,requests,admin=false}:{bookings:Booking[];requests:Enquiry[];admin?:boolean}) {
  return <div className="mt-10 space-y-12"><section><h2 className="mb-5 text-2xl font-bold">{admin ? "Equipment bookings" : "My bookings"}</h2><div className="grid gap-5">{!bookings.length && <p className="surface">No bookings yet. <Link href="/equipment" className="text-buet-red underline">Browse equipment</Link>.</p>}{bookings.map(booking=><article className="surface" key={booking.id}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-bold">{mockEquipment.find(e=>e.id===booking.equipment_id)?.name}</h3><Badge className="capitalize" variant={booking.status==="approved" ? "success" : "secondary"}>{booking.status}</Badge></div><p className="mt-3">{booking.date} · {booking.slot} (Dhaka time)</p><p className="mt-2 break-words font-medium">{booking.project} · {booking.material}</p><p className="text-sm text-neutral-600">Machine estimate: BDT {booking.estimate}</p><p className="mt-2 break-all font-mono text-xs text-neutral-500">{booking.id}</p>{admin && <div className="mt-4 space-y-2 text-sm"><p>{booking.name} · {booking.email} · {booking.organisation}</p><p>Training: {booking.training}</p><p>Verify training and the final quote with the applicant before approving.</p></div>}{booking.upload_id && <a className="mt-3 block break-all text-sm text-buet-red underline" href={`/api/uploads/${booking.upload_id}`}>Download {booking.upload_name}</a>}<RecordActions id={booking.id} kind="bookings" status={booking.status} admin={admin}/></article>)}</div></section>
    <section><h2 className="mb-5 text-2xl font-bold">{admin ? "Service requests" : "My requests"}</h2><div className="grid gap-5">{!requests.length && <p className="surface">No requests submitted while signed in.</p>}{requests.map(request=><article className="surface" key={request.id}><div className="flex flex-wrap justify-between gap-3"><h3 className="text-xl font-bold">{request.subject}</h3><Badge variant="secondary" className="capitalize">{request.status}</Badge></div><p className="mt-3 whitespace-pre-wrap break-words">{request.details}</p>{Object.entries(JSON.parse(request.extra) as Record<string,string>).map(([key,value])=><p className="mt-2 text-sm" key={key}><span className="capitalize">{key}</span>: {value}</p>)}<p className="mt-3 break-all font-mono text-xs text-neutral-500">{request.id}</p>{admin && <><p className="mt-3 break-words text-sm">{request.name} · {request.email} · {request.organisation}</p><RecordActions id={request.id} kind="requests" status={request.status} admin/></>}</article>)}</div></section></div>;
}
