"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import type { Equipment } from "@/data/fixtures/equipment";
import { dhakaDate } from "@/lib/booking";
const steps = ["Eligibility", "Schedule", "Project", "Review"];
export function BookingForm({equipment}:{equipment:Equipment}) {
  const [step,setStep] = useState(0), [date,setDate] = useState(""), [slot,setSlot] = useState(""), [available,setAvailable] = useState<string[]>([]), [loading,setLoading] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState(""), [reference,setReference] = useState(""), [file,setFile] = useState<File | null>(null), [uploadId,setUploadId] = useState("");
  const [values,setValues] = useState({training:"",project:"",organisation:"",material:"",agreement:false});
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { heading.current?.focus(); }, [step,reference]);
  useEffect(() => {
    setSlot(""); setAvailable([]); if (!date) return;
    const controller = new AbortController(); setLoading(true); setError("");
    fetch(`/api/bookings?equipment=${equipment.id}&date=${date}`, {signal:controller.signal}).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setAvailable(result.slots); }).catch(error => {if (error.name !== "AbortError") setError("Could not load availability. Select the date again to retry.");}).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [date,equipment.id]);
  async function submit(event:FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError("");
    if (step < 3) {setStep(step + 1); return;}
    setBusy(true);
    try {
      let attachment = uploadId;
      if (file && !attachment) { const data = new FormData(); data.set("file",file); const response = await fetch("/api/uploads",{method:"POST",body:data}); const result = await response.json(); if (!response.ok) throw new Error(result.error); attachment = result.id; setUploadId(attachment); }
      const response = await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,equipmentId:equipment.id,date,slot,uploadId:attachment})});
      const result = await response.json(); if (!response.ok) { if (response.status === 409) {setStep(1); setSlot(""); setDate("");} throw new Error(result.error); } setReference(result.id);
    } catch(error) {setError(error instanceof Error ? error.message : "Unable to save booking. Please try again.");} finally {setBusy(false);}
  }
  if (reference) return <div className="surface text-center" role="status"><h2 ref={heading} tabIndex={-1} className="text-2xl font-bold text-buet-red-dark">Booking request saved</h2><p className="mt-4">{equipment.name} · {date} · {slot} (Dhaka time)</p><p className="my-5 break-all font-mono text-sm">{reference}</p><p className="mb-6 text-neutral-600">Your slot is held pending staff review of training, materials, and pricing. Check your dashboard for approval before visiting.</p><Button asChild><Link href="/dashboard">View my bookings</Link></Button></div>;
  return <div><ol aria-label="Booking progress" className="mb-6 grid grid-cols-4 gap-2">{steps.map((label,index) => <li key={label} aria-current={index === step ? "step" : undefined} className={`border-t-4 py-3 text-xs sm:text-sm ${index <= step ? "border-buet-red text-buet-red font-semibold" : "border-neutral-300 text-neutral-500"}`}>{index+1}. {label}</li>)}</ol>
    <form className="surface space-y-6" onSubmit={submit}><h2 ref={heading} tabIndex={-1} className="text-2xl font-bold text-buet-red-dark">{steps[step]}</h2>
      {step === 0 && <><p>Required training: <strong>{equipment.trainingRequired}</strong>. Staff verify certification before approving access.</p><label className="form-label">Your training or support needs<textarea className="form-field min-h-28" required minLength={3} maxLength={500} value={values.training} onChange={e => setValues({...values,training:e.target.value})} placeholder="Describe your completed training, or request a supervised session."/></label><Link className="text-sm text-buet-red underline" href="/training/register">Need training? Register for a course</Link></>}
      {step === 1 && <><label className="form-label">Session date<input type="date" className="form-field" required min={dhakaDate()} value={date} onChange={e => setDate(e.target.value)}/></label><p className="text-sm text-neutral-600">Sunday–Thursday, from tomorrow up to 90 days ahead. Thursday closes at 13:00. All times are Asia/Dhaka.</p><fieldset><legend className="mb-3 text-sm font-semibold">Available two-hour sessions</legend>{loading ? <p role="status">Loading availability…</p> : available.length ? <div className="grid gap-3 sm:grid-cols-3">{available.map(time => <label key={time} className={`flex cursor-pointer items-center gap-3 rounded-md border p-4 ${slot === time ? "border-buet-red bg-buet-red/5" : "border-neutral-300"}`}><input type="radio" required name="slot" checked={slot === time} onChange={() => setSlot(time)}/>{time}</label>)}</div> : <p role="status" className="text-sm text-neutral-600">{date ? "No sessions on this date. Choose another working day." : "Select a date to see sessions."}</p>}</fieldset></>}
      {step === 2 && <><label className="form-label">Project title<input className="form-field" required minLength={3} maxLength={200} value={values.project} onChange={e => setValues({...values,project:e.target.value})}/></label><label className="form-label">Department or organisation<input className="form-field" required minLength={2} maxLength={200} value={values.organisation} onChange={e => setValues({...values,organisation:e.target.value})}/></label><label className="form-label">Primary material<select className="form-field" required value={values.material} onChange={e => setValues({...values,material:e.target.value})}><option value="">Select an approved material</option>{equipment.supportedMaterials.map(m => <option key={m}>{m}</option>)}</select></label><label className="form-label">Design file (optional)<input type="file" accept=".stl,.step,.stp,.dxf,.pdf" className="form-field" onChange={e => {const selected=e.target.files?.[0] || null; if (selected && (selected.size > 10*1024*1024 || !/\.(stl|step|stp|dxf|pdf)$/i.test(selected.name))) {setError("Choose an STL, STEP, DXF or PDF file up to 10 MB.");e.target.value="";setFile(null);setUploadId("");return;}setFile(selected);setUploadId("");setError("");}}/><span className="text-xs text-neutral-500">STL, STEP, DXF or PDF, up to 10 MB. {file && `Selected: ${file.name}`}</span></label></>}
      {step === 3 && <><dl className="grid gap-4 rounded-md bg-neutral-50 p-5 sm:grid-cols-2">{[["Machine",equipment.name],["Session",`${date} · ${slot}`],["Project",values.project],["Organisation",values.organisation],["Material",values.material],["Training",values.training],["Attachment",file?.name || "None"],["Machine time estimate",`BDT ${equipment.externalRate*2} (2 hours)`]].map(([label,value]) => <div key={label} className="min-w-0"><dt className="text-sm text-neutral-500">{label}</dt><dd className="break-words font-medium">{value}</dd></div>)}</dl><p className="text-sm text-neutral-600">Estimate uses the external rate. Eligible BUET users may receive the internal rate of BDT {equipment.internalRate}/hour after staff verification. Materials cost extra; staff confirm the final quote. Published rates are sample data.</p><label className="flex items-start gap-3 text-sm"><input type="checkbox" required className="mt-1" checked={values.agreement} onChange={e => setValues({...values,agreement:e.target.checked})}/><span>I agree to follow lab safety protocols, use approved materials and PPE, clean the work area, and give at least 24 hours’ cancellation notice. I understand staff must approve this request before machine use.</span></label></>}
      {error && <p role="alert" className="form-error">{error}</p>}<div className="flex justify-between gap-4 border-t pt-5"><Button type="button" variant="outline" disabled={step===0 || busy} onClick={() => {setStep(step-1);setError("");}}>Back</Button><Button type="submit" disabled={busy || (step===1 && (!slot || loading))}>{busy ? "Saving…" : step===3 ? "Submit booking request" : "Continue"}</Button></div>
    </form></div>;
}
